### ISSUE TITLE
Support multiple DarkFramePreprocessors

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-darkframes#19]
I believe (but have not rigorously verified) that if two `DarkFramePreprocessors` are applied, they will interfere. The outer one will see the `trigger` messages added by the inner one, and try to take a dark frame for a dark frame (if that makes sense...).

We briefly tried this at CSX and that theory seemed to be correct; at least we can say for sure that trying two nested preprocessors failed.

The fix I have in mind is to let `DarkFramePreprocessors` recognize `trigger` messages that came from itself by using a special convention in the `group`---that is instead of `'trigger-<uuid>'`, do `'trigger-dark-frame-preprocessor-<uuid>'`. The content of the group has no meaning to any other part of our system.

**Comment by danielballan** [comment]
xref https://github.com/NSLS-II-CSX/xf23id1_profiles/pull/32
cc @ambarb, @jklynch, @mrakitin

**Comment by jklynch** [comment]
This seems like a reasonable plan, but does it ever make sense to have multiple DarkFrameProcessors?

**Comment by danielballan** [comment]
A fair question. It's come up in two situations:

- At beamlines where they switch between two or more detectors
- At CSX, they want to make dark frames with multiple gain settings. For the purposes of the Pilot demo in January, we did just one gain setting, but to make this actually useful we need to cover as many as three. They won't all be needed all the time, so we need a convenient way to users to switch them on and off individually.

Binding a `DarkFramePreprocessor` to one `detector`, one `dark_plan`, and one `stream_name` keeps the user API and the implementation simple (or as simple as we can make it...). Given a choice between making `DarkFramePreprocessor.__init__` and the underlying implementation more complex or telling people, "Build multiple `DarkFramePreprocessor`s if you have multiple detectors and/or multiple dark frames with different settings per detector", the latter seems easier to manage.

**Comment by ambarb** [comment]
IS it useful to include flatfield and the image correction/normalization/blemish/broken pixel maps?

**Comment by danielballan** [comment]
Based on my understanding so far, from a software perspective we can treat flatfield the same as a dark frame: it will just have a different `dark_plan` and `stream_name`.

I think the correction/normalization/blemish/broken pixel maps are in a separate category. We have never nailed down our story about how to handle that. Theories have included:

* Stash that kind of thing in `RE.md`, where it would end up in the RunStart document (not sure I like this).
* Add a "soft `Signal`" to the detector that, when read, returns the broken pixel map (for example). Mark the `Signal` as `kind='config'`, such that `detector.describe()` will include it. The map would end up in the EventDescriptor's `'configuration'` field. That may be the right place for it. It belongs close to the relevant _hardware_ not with metadata about the particular _plan_ that happens to be run.
