### ISSUE TITLE
Do not require collect_asset_docs method.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-darkframes#27]
The method `collect_asset_docs` is _optional_ API on readable devices, but bluesky-darkframes treats it as required API.

**Comment by danielballan** [comment]
That link above doesn't look like a proper link.

We need to check whether a given device `hasattr(device, "collect_asset_docs")` and only call it if so. Similar to https://github.com/bluesky/bluesky/blob/3e298fde0abfba8ad99aea535ff4ee37c79d755a/bluesky/bundlers.py#L202

**Comment by ke-zhang-rd** [comment]
Just update link. 
If device doesn't have `collect_asset_docs` method. Do we need to construct `self. _asset_docs_cache` in another way or leave it as a empty list?

**Comment by danielballan** [comment]
Leaving it as an empty list should work, I think.

**Comment by ke-zhang-rd** [comment]
Closed by #29
